### PR TITLE
v2 api support

### PR DESCRIPTION
**Pull request by babldev**
Pagerduty doesn't support creating v1 tokens anymore. Use the v2 api https://v2.developer.pagerduty.com/

### CODE REVIEW

**Comment by babldev** [comment]
🚀

**Comment by babldev** [comment]
dang

**Comment by glenrobertson** [comment]
👍

**Comment by babldev** [comment]
screen shot 2018-05-15 at 6 59 11 pm

**Comment by babldev** [comment]
nope

**Comment by glenrobertson** [comment]
the button needs to have a higher resolution to be pressed

**Comment by babldev** [comment]
OK let me try that
screen shot 2018-05-15 at 7 05 18 pm

**Comment by babldev** [comment]
THANK YOU LIZ

**Pull request merged**
