### PR TITLE
Show alert timezone

### PR DESCRIPTION
**Pull request by pnest**
Show alert timezone along with time.

Before:
image

After:
image

### CODE REVIEW

**Comment by pnest** [comment]
ptal @andelink @m25746 @dBriones3 @billmwong

**Review by dBriones3 — APPROVED** [review]

**Review by andelink — APPROVED** [review]
👍👍👍

**Review by billmwong — APPROVED** [review]
cool!

**Comment by pnest** [comment]
ptal @acl-opsreview

**Comment by pnest** [comment]
ptal @lyft/acl-opsreview

**Review by m25746 — APPROVED** [review]
Thanks!

**Comment by pnest** [comment]
ptal @lyft/acl-opsreview

**Review by aakside — APPROVED** [review]

**Review by rmtzcx — APPROVED** [review]

**Pull request merged**
